NDefines.NCharacter.FERTILITY_BASE_MULT = 0.4
NDefines.NCharacter.SECONDARY_SPOUSE_FERTILITY_MULT = 0.25
NDefines.NEngine.EVENT_PROCESS_OFFSET = 100
NDefines.NEngine.COURTIER_EVENT_PROCESS_OFFSET = 255
NDefines.NEngine.COURT_PRUNE_SIZE = 1
NDefines.NEngine.PRUNE_MINIMAL_AGE = 1